/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequestCutiRouteImport } from './routes/request-cuti'
import { Route as AuthenticatedCabangRouteImport } from './routes/_authenticated/cabang'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFormatWhatsappRouteImport } from './routes/_authenticated/format-whatsapp'
import { Route as AuthenticatedGajiPokokRouteImport } from './routes/_authenticated/gaji-pokok'
import { Route as AuthenticatedJabatanRouteImport } from './routes/_authenticated/jabatan'
import { Route as AuthenticatedKaryawanRouteImport } from './routes/_authenticated/karyawan'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedPotonganRouteImport } from './routes/_authenticated/potongan'
import { Route as AuthenticatedProsesGajiRouteImport } from './routes/_authenticated/proses-gaji'
import { Route as AuthenticatedRekeningBankRouteImport } from './routes/_authenticated/rekening-bank'
import { Route as AuthenticatedRingkasanWhatsappRouteImport } from './routes/_authenticated/ringkasan-whatsapp'
import { Route as AuthenticatedSlipGajiRouteImport } from './routes/_authenticated/slip-gaji'
import { Route as AuthenticatedTunjanganRouteImport } from './routes/_authenticated/tunjangan'
import { Route as AuthenticatedHrKalenderCutiRouteImport } from './routes/_authenticated/hr/kalender-cuti'
import { Route as AuthenticatedHrRekapAbsenRouteImport } from './routes/_authenticated/hr/rekap-absen'
import { Route as AuthenticatedHrRequestCutiRouteImport } from './routes/_authenticated/hr/request-cuti'
import { Route as AuthenticatedHrResignRouteImport } from './routes/_authenticated/hr/resign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestCutiRoute = RequestCutiRouteImport.update({
  id: '/request-cuti',
  path: '/request-cuti',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCabangRoute = AuthenticatedCabangRouteImport.update({
  id: '/cabang',
  path: '/cabang',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormatWhatsappRoute =
  AuthenticatedFormatWhatsappRouteImport.update({
    id: '/format-whatsapp',
    path: '/format-whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGajiPokokRoute = AuthenticatedGajiPokokRouteImport.update({
  id: '/gaji-pokok',
  path: '/gaji-pokok',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJabatanRoute = AuthenticatedJabatanRouteImport.update({
  id: '/jabatan',
  path: '/jabatan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKaryawanRoute = AuthenticatedKaryawanRouteImport.update({
  id: '/karyawan',
  path: '/karyawan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPotonganRoute = AuthenticatedPotonganRouteImport.update({
  id: '/potongan',
  path: '/potongan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProsesGajiRoute = AuthenticatedProsesGajiRouteImport.update({
  id: '/proses-gaji',
  path: '/proses-gaji',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRekeningBankRoute =
  AuthenticatedRekeningBankRouteImport.update({
    id: '/rekening-bank',
    path: '/rekening-bank',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRingkasanWhatsappRoute =
  AuthenticatedRingkasanWhatsappRouteImport.update({
    id: '/ringkasan-whatsapp',
    path: '/ringkasan-whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSlipGajiRoute = AuthenticatedSlipGajiRouteImport.update({
  id: '/slip-gaji',
  path: '/slip-gaji',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTunjanganRoute = AuthenticatedTunjanganRouteImport.update({
  id: '/tunjangan',
  path: '/tunjangan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrKalenderCutiRoute =
  AuthenticatedHrKalenderCutiRouteImport.update({
    id: '/hr/kalender-cuti',
    path: '/hr/kalender-cuti',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrRekapAbsenRoute =
  AuthenticatedHrRekapAbsenRouteImport.update({
    id: '/hr/rekap-absen',
    path: '/hr/rekap-absen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrRequestCutiRoute =
  AuthenticatedHrRequestCutiRouteImport.update({
    id: '/hr/request-cuti',
    path: '/hr/request-cuti',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrResignRoute = AuthenticatedHrResignRouteImport.update({
  id: '/hr/resign',
  path: '/hr/resign',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/request-cuti': typeof RequestCutiRoute
  '/cabang': typeof AuthenticatedCabangRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/format-whatsapp': typeof AuthenticatedFormatWhatsappRoute
  '/gaji-pokok': typeof AuthenticatedGajiPokokRoute
  '/jabatan': typeof AuthenticatedJabatanRoute
  '/karyawan': typeof AuthenticatedKaryawanRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/potongan': typeof AuthenticatedPotonganRoute
  '/proses-gaji': typeof AuthenticatedProsesGajiRoute
  '/rekening-bank': typeof AuthenticatedRekeningBankRoute
  '/ringkasan-whatsapp': typeof AuthenticatedRingkasanWhatsappRoute
  '/slip-gaji': typeof AuthenticatedSlipGajiRoute
  '/tunjangan': typeof AuthenticatedTunjanganRoute
  '/hr/kalender-cuti': typeof AuthenticatedHrKalenderCutiRoute
  '/hr/rekap-absen': typeof AuthenticatedHrRekapAbsenRoute
  '/hr/request-cuti': typeof AuthenticatedHrRequestCutiRoute
  '/hr/resign': typeof AuthenticatedHrResignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/request-cuti': typeof RequestCutiRoute
  '/cabang': typeof AuthenticatedCabangRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/format-whatsapp': typeof AuthenticatedFormatWhatsappRoute
  '/gaji-pokok': typeof AuthenticatedGajiPokokRoute
  '/jabatan': typeof AuthenticatedJabatanRoute
  '/karyawan': typeof AuthenticatedKaryawanRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/potongan': typeof AuthenticatedPotonganRoute
  '/proses-gaji': typeof AuthenticatedProsesGajiRoute
  '/rekening-bank': typeof AuthenticatedRekeningBankRoute
  '/ringkasan-whatsapp': typeof AuthenticatedRingkasanWhatsappRoute
  '/slip-gaji': typeof AuthenticatedSlipGajiRoute
  '/tunjangan': typeof AuthenticatedTunjanganRoute
  '/hr/kalender-cuti': typeof AuthenticatedHrKalenderCutiRoute
  '/hr/rekap-absen': typeof AuthenticatedHrRekapAbsenRoute
  '/hr/request-cuti': typeof AuthenticatedHrRequestCutiRoute
  '/hr/resign': typeof AuthenticatedHrResignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/request-cuti': typeof RequestCutiRoute
  '/_authenticated/cabang': typeof AuthenticatedCabangRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/format-whatsapp': typeof AuthenticatedFormatWhatsappRoute
  '/_authenticated/gaji-pokok': typeof AuthenticatedGajiPokokRoute
  '/_authenticated/jabatan': typeof AuthenticatedJabatanRoute
  '/_authenticated/karyawan': typeof AuthenticatedKaryawanRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/potongan': typeof AuthenticatedPotonganRoute
  '/_authenticated/proses-gaji': typeof AuthenticatedProsesGajiRoute
  '/_authenticated/rekening-bank': typeof AuthenticatedRekeningBankRoute
  '/_authenticated/ringkasan-whatsapp': typeof AuthenticatedRingkasanWhatsappRoute
  '/_authenticated/slip-gaji': typeof AuthenticatedSlipGajiRoute
  '/_authenticated/tunjangan': typeof AuthenticatedTunjanganRoute
  '/_authenticated/hr/kalender-cuti': typeof AuthenticatedHrKalenderCutiRoute
  '/_authenticated/hr/rekap-absen': typeof AuthenticatedHrRekapAbsenRoute
  '/_authenticated/hr/request-cuti': typeof AuthenticatedHrRequestCutiRoute
  '/_authenticated/hr/resign': typeof AuthenticatedHrResignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/request-cuti'
    | '/cabang'
    | '/dashboard'
    | '/format-whatsapp'
    | '/gaji-pokok'
    | '/jabatan'
    | '/karyawan'
    | '/laporan'
    | '/pengaturan'
    | '/potongan'
    | '/proses-gaji'
    | '/rekening-bank'
    | '/ringkasan-whatsapp'
    | '/slip-gaji'
    | '/tunjangan'
    | '/hr/kalender-cuti'
    | '/hr/rekap-absen'
    | '/hr/request-cuti'
    | '/hr/resign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/request-cuti'
    | '/cabang'
    | '/dashboard'
    | '/format-whatsapp'
    | '/gaji-pokok'
    | '/jabatan'
    | '/karyawan'
    | '/laporan'
    | '/pengaturan'
    | '/potongan'
    | '/proses-gaji'
    | '/rekening-bank'
    | '/ringkasan-whatsapp'
    | '/slip-gaji'
    | '/tunjangan'
    | '/hr/kalender-cuti'
    | '/hr/rekap-absen'
    | '/hr/request-cuti'
    | '/hr/resign'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/request-cuti'
    | '/_authenticated/cabang'
    | '/_authenticated/dashboard'
    | '/_authenticated/format-whatsapp'
    | '/_authenticated/gaji-pokok'
    | '/_authenticated/jabatan'
    | '/_authenticated/karyawan'
    | '/_authenticated/laporan'
    | '/_authenticated/pengaturan'
    | '/_authenticated/potongan'
    | '/_authenticated/proses-gaji'
    | '/_authenticated/rekening-bank'
    | '/_authenticated/ringkasan-whatsapp'
    | '/_authenticated/slip-gaji'
    | '/_authenticated/tunjangan'
    | '/_authenticated/hr/kalender-cuti'
    | '/_authenticated/hr/rekap-absen'
    | '/_authenticated/hr/request-cuti'
    | '/_authenticated/hr/resign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RequestCutiRoute: typeof RequestCutiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-cuti': {
      id: '/request-cuti'
      path: '/request-cuti'
      fullPath: '/request-cuti'
      preLoaderRoute: typeof RequestCutiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cabang': {
      id: '/_authenticated/cabang'
      path: '/cabang'
      fullPath: '/cabang'
      preLoaderRoute: typeof AuthenticatedCabangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/format-whatsapp': {
      id: '/_authenticated/format-whatsapp'
      path: '/format-whatsapp'
      fullPath: '/format-whatsapp'
      preLoaderRoute: typeof AuthenticatedFormatWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gaji-pokok': {
      id: '/_authenticated/gaji-pokok'
      path: '/gaji-pokok'
      fullPath: '/gaji-pokok'
      preLoaderRoute: typeof AuthenticatedGajiPokokRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jabatan': {
      id: '/_authenticated/jabatan'
      path: '/jabatan'
      fullPath: '/jabatan'
      preLoaderRoute: typeof AuthenticatedJabatanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/karyawan': {
      id: '/_authenticated/karyawan'
      path: '/karyawan'
      fullPath: '/karyawan'
      preLoaderRoute: typeof AuthenticatedKaryawanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/potongan': {
      id: '/_authenticated/potongan'
      path: '/potongan'
      fullPath: '/potongan'
      preLoaderRoute: typeof AuthenticatedPotonganRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proses-gaji': {
      id: '/_authenticated/proses-gaji'
      path: '/proses-gaji'
      fullPath: '/proses-gaji'
      preLoaderRoute: typeof AuthenticatedProsesGajiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rekening-bank': {
      id: '/_authenticated/rekening-bank'
      path: '/rekening-bank'
      fullPath: '/rekening-bank'
      preLoaderRoute: typeof AuthenticatedRekeningBankRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ringkasan-whatsapp': {
      id: '/_authenticated/ringkasan-whatsapp'
      path: '/ringkasan-whatsapp'
      fullPath: '/ringkasan-whatsapp'
      preLoaderRoute: typeof AuthenticatedRingkasanWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/slip-gaji': {
      id: '/_authenticated/slip-gaji'
      path: '/slip-gaji'
      fullPath: '/slip-gaji'
      preLoaderRoute: typeof AuthenticatedSlipGajiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tunjangan': {
      id: '/_authenticated/tunjangan'
      path: '/tunjangan'
      fullPath: '/tunjangan'
      preLoaderRoute: typeof AuthenticatedTunjanganRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/kalender-cuti': {
      id: '/_authenticated/hr/kalender-cuti'
      path: '/hr/kalender-cuti'
      fullPath: '/hr/kalender-cuti'
      preLoaderRoute: typeof AuthenticatedHrKalenderCutiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/rekap-absen': {
      id: '/_authenticated/hr/rekap-absen'
      path: '/hr/rekap-absen'
      fullPath: '/hr/rekap-absen'
      preLoaderRoute: typeof AuthenticatedHrRekapAbsenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/request-cuti': {
      id: '/_authenticated/hr/request-cuti'
      path: '/hr/request-cuti'
      fullPath: '/hr/request-cuti'
      preLoaderRoute: typeof AuthenticatedHrRequestCutiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/resign': {
      id: '/_authenticated/hr/resign'
      path: '/hr/resign'
      fullPath: '/hr/resign'
      preLoaderRoute: typeof AuthenticatedHrResignRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCabangRoute: typeof AuthenticatedCabangRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFormatWhatsappRoute: typeof AuthenticatedFormatWhatsappRoute
  AuthenticatedGajiPokokRoute: typeof AuthenticatedGajiPokokRoute
  AuthenticatedJabatanRoute: typeof AuthenticatedJabatanRoute
  AuthenticatedKaryawanRoute: typeof AuthenticatedKaryawanRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedPotonganRoute: typeof AuthenticatedPotonganRoute
  AuthenticatedProsesGajiRoute: typeof AuthenticatedProsesGajiRoute
  AuthenticatedRekeningBankRoute: typeof AuthenticatedRekeningBankRoute
  AuthenticatedRingkasanWhatsappRoute: typeof AuthenticatedRingkasanWhatsappRoute
  AuthenticatedSlipGajiRoute: typeof AuthenticatedSlipGajiRoute
  AuthenticatedTunjanganRoute: typeof AuthenticatedTunjanganRoute
  AuthenticatedHrKalenderCutiRoute: typeof AuthenticatedHrKalenderCutiRoute
  AuthenticatedHrRekapAbsenRoute: typeof AuthenticatedHrRekapAbsenRoute
  AuthenticatedHrRequestCutiRoute: typeof AuthenticatedHrRequestCutiRoute
  AuthenticatedHrResignRoute: typeof AuthenticatedHrResignRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCabangRoute: AuthenticatedCabangRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFormatWhatsappRoute: AuthenticatedFormatWhatsappRoute,
  AuthenticatedGajiPokokRoute: AuthenticatedGajiPokokRoute,
  AuthenticatedJabatanRoute: AuthenticatedJabatanRoute,
  AuthenticatedKaryawanRoute: AuthenticatedKaryawanRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedPotonganRoute: AuthenticatedPotonganRoute,
  AuthenticatedProsesGajiRoute: AuthenticatedProsesGajiRoute,
  AuthenticatedRekeningBankRoute: AuthenticatedRekeningBankRoute,
  AuthenticatedRingkasanWhatsappRoute: AuthenticatedRingkasanWhatsappRoute,
  AuthenticatedSlipGajiRoute: AuthenticatedSlipGajiRoute,
  AuthenticatedTunjanganRoute: AuthenticatedTunjanganRoute,
  AuthenticatedHrKalenderCutiRoute: AuthenticatedHrKalenderCutiRoute,
  AuthenticatedHrRekapAbsenRoute: AuthenticatedHrRekapAbsenRoute,
  AuthenticatedHrRequestCutiRoute: AuthenticatedHrRequestCutiRoute,
  AuthenticatedHrResignRoute: AuthenticatedHrResignRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RequestCutiRoute: RequestCutiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
